### ISSUE TITLE
Problem converting group-name to group id

### ISSUE THREAD

**Issue by jdhyun09** [dvlprsh/brightid-onchain-demo#11]
SemaphoreGroups issue:
group id must be < SNARK_SCALAR_FIELD

If ethers.utils.formatBytes32String("<group-name>") is used, most have the same issue as above.
There should be a good way to convert group-name to (uint256)groupid.

**Comment by cedoor** [comment]
Hey, you could convert your string to 31 bytes rather than 32. You can edit the `farmatBytes32String` original function: https://github.com/ethers-io/ethers.js/blob/master/packages/strings/src.ts/bytes32.ts#L9.
